### ISSUE TITLE
Adopt current process cwd.

### ISSUE THREAD

**Issue by byehack** [mihai-vlc/path-autocomplete#116]
![image](https://user-images.githubusercontent.com/26390254/188281692-f899ecdf-ee7f-4c2c-82ec-0720b1deaa08.png)

Expected to suggest "E:" items.

**Comment by ionutvmi** [comment]
The relative completion are based on the current document/file.

I'm not sure how we could get access to that `cwd` folder inside a notebook.
Feel free to explore and open a PR if you find a good solution for this use case.
