### ISSUE TITLE
Make relative paths relative to the open directory

### ISSUE THREAD

**Issue by kendonB** [mihai-vlc/path-autocomplete#117]
It is common in vscode for users to 1) work on projects using a workspace, 2) assume the working directory is relative to the top level of that workspace.

Thus, it seems most natural that relative paths look to see if a workspace is open and, if so, assume relative paths relative to the directory of that workspace. Could that be changed? Or made as an option?

**Comment by ionutvmi** [comment]
You can try to use path mappings for changing the root folder.

One of these should work for your use case:
```
"path-autocomplete.pathMappings": {
        "/": "${folder}/",
       "$root": "${folder}/"
}
```

Please close the issue if this solution solved it.
