### ISSUE TITLE
Incorrect path for xxx.module.scss files

### ISSUE THREAD

**Issue by Ice-mourne** [mihai-vlc/path-autocomplete#120]
scss files name.module.scss are imported as name.module then it should be name.module.scss
![image](https://user-images.githubusercontent.com/77716865/201532359-d418550d-7398-4921-a797-bd2330bfa729.png)

It gives this
![image](https://user-images.githubusercontent.com/77716865/201532399-058a6286-51a5-4727-81e9-6c7b04a834ca.png)
Should be this
![image](https://user-images.githubusercontent.com/77716865/201532422-52795f27-10eb-4807-a32b-5f62b8c82b1f.png)

I'm pretty sure CSS, SCSS files always have to end with .CSS, .SCSS regardless of the module I have in mine
VS code editor in case that matters

**Comment by ionutvmi** [comment]
hi @Ice-mourne ,

can you try to enable `path-autocomplete.extensionOnImport` in the settings ?

**Comment by Ice-mourne** [comment]
That solves that problem but creates another one
![image](https://user-images.githubusercontent.com/77716865/201538061-f5afbaba-7d4f-4dd7-930e-b7ae54e3a8e2.png)
![image](https://user-images.githubusercontent.com/77716865/201538077-a081398e-ea32-4675-b2fb-cb134a6f11a0.png)

**Comment by ionutvmi** [comment]
Hi @Ice-mourne ,

if you don't want certain files to have extension you can use transformations

something along these lines should work:
```json
"path-autocomplete.transformations": [{
    "type": "replace",
    "parameters": ["\.tsx", ""],
    "when": {
        "fileName": "\\.tsx$"
    }
}],
```

**Comment by Ice-mourne** [comment]
While this is a solution it feels like a workaround for something that shouldn't happen in the first place  
Importing .ts, .tsx in a .ts, .tsx file always seems to give this error maybe this should be the default behavior
But at the same time, it probably will be a problem in some other cases maybe

This setting ``path-autocomplete.extensionOnImport``
And this should be default in .ts, .tsx files
```JSON
"path-autocomplete.transformations": [
   {
      "type": "replace",
      "parameters": ["\\.tsx", ""],
      "when": {
         "fileName": "\\.tsx$"
      }
   },
   {
      "type": "replace",
      "parameters": ["\\.ts", ""],
      "when": {
         "fileName": "\\.ts$"
      }
   }
]
  ```
  
  But other than that thx for making the extension and helping me fix this problem
