### ISSUE TITLE
support trim specific extension on import

### ISSUE THREAD

**Issue by tjx666** [mihai-vlc/path-autocomplete#123]
In normal web project, when import `js/ts/jsx/tsx/mts/mjs/cjs` they needn't complete extension. But like `less/scss/png` etc need.

So, it would be better to have a configuration to configure to make only trim specific extension on import.

@mihai-vlc

**Comment by tjx666** [comment]
@mihai-vlc My use case is that in my project, vscode builtin typescript relative path module suggestion doesn't work. So I want to use this extension to support path suggestion.
But you can see this extension provide suggestion with file extension:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/216357142-30a36ed4-6a07-4ab3-a1ba-cdac825a9738.png">

For now, we have setting `path-autocomplete.extensionOnImport`, but that can't solve my need.

I want to trim file extension for `ts/js`, but not for `css/scss/less` etc

**Comment by mihai-vlc** [comment]
Hi @tjx666 ,

Can you try configuring the language specific settings in v1.23 ?

```json
    "path-autocomplete.extensionOnImport": true,
    "[typescript]": {
        "path-autocomplete.extensionOnImport": false,
    },
```

Please feel free to reopen the ticket if you still encounter issues.

**Comment by mihai-vlc** [comment]
You may also want to combine this with `path-autocomplete.transformations` if you want to remove the extension for certain files but keep it for others.

**Comment by tjx666** [comment]
I need use `autocomplete.transformations` setting to restore scss/less which is a little complex.

My thought is to let `path-autocomplete.extensionOnImport` setting support object value. like:

```json
{
    "path-autocomplete.extensionOnImport": {
        "*.{ts,tsx,js,jsx}": false
    }
}
```

**Comment by mihai-vlc** [comment]
would something like this work ?

```json
"path-autocomplete.extensionOnImport": true,
    "path-autocomplete.transformations": [
        {
            "type": "replace",
            "parameters": [
                "\\.\\w+$",
                ""
            ],
            "when": {
                "fileName": "\\.(ts|tsx|js|jsx)$"
            }
        }
    ],
```

**Comment by tjx666** [comment]
> would something like this work ?

Nice work.
