### ISSUE TITLE
Possible to customize the trigger keyboard command?

### ISSUE THREAD

**Issue by zacksmash** [mihai-vlc/path-autocomplete#124]
I don't want to have to type / to trigger the suggestion panel, I want to just start typing and have it read from my path mappings.

For example, in Liquid I would have this:

```json
"path-autocomplete.pathMappings": {
    "/": "${folder}/snippets"
}
```

```liquid
{% render '' %}
```

when my cursor is between the two quotes, I would like the panel to popup with my snippets list where I can just start typing the name of a snippet to auto-fill, without the preceding /. Is this currently possible?

**Comment by mihai-vlc** [comment]
You should get completions if you press `Ctrl + Space`
You will get completions from all the sources, so you may need to look at the bottom of the list to find the files from that folder.

You may also need to configure the `$root` property in the path mappings.

```
"path-autocomplete.pathMappings": {
    "$root": "${folder}/snippets"
}
```
