### ISSUE TITLE
how to include from root path

### ISSUE THREAD

**Issue by cavalier501** [mihai-vlc/path-autocomplete#125]
it' s a good work that helps a lot. But it seems that Path Autocomplete can't include root path (starting with /), and path starting with "/" may be understood as current workspace, can anyone help with this?

**Comment by mihai-vlc** [comment]
have you tried something like this ?

```json
"path-autocomplete.pathMappings": {
    "/": "${folder}"
}

```

**Comment by cavalier501** [comment]
> 

thanks for your reply, but it still dosen't work. 
I applied it in the "settings.json" file, but Path Autocomplete still understood "/" as current workspace

**Comment by cavalier501** [comment]
> have you tried something like this ?
> 
> ```json
> "path-autocomplete.pathMappings": {
>     "/": "${folder}"
> }
> ```

thanks for your reply, but it still dosen't work.
I applied it in the "settings.json" file, but Path Autocomplete still understood "/" as current workspace

**Comment by mihai-vlc** [comment]
Maybe I misunderstood what you are trying to do.

By default `/` will point to the root of the partition.
You would have to configure `/` -> `${folder}` if you want to get files relative to the current workspace.

You can also specify a specific folder if you want the root to be outside the project:
```
"/": "/some/other/folder"
```
