### ISSUE TITLE
Hope to provide support for the Monorepo project

### ISSUE THREAD

**Issue by maqinghao** [mihai-vlc/path-autocomplete#128]
Aliases support the definition of each sub project as the root directory under the current packages

**Comment by mihai-vlc** [comment]
Version 1.25.0 added support for conditional path mappings.

- Adds support for conditional path mappings

```jsonc
  "path-autocomplete.pathMappings": {
    "$root": {
      "conditions": [
        {
          "when": "**/packages/math/**",
          "value": "${folder}/packages/math"
        },
        {
          "when": "**/packages/ui/**",
          "value": "${folder}/packages/ui"
        }
      ]
    }
  },
```


Can you try it out and let me know if it works for your use case ?
